SUBROUTINE TESTA_CONDICIONAMENTO(KGLOBAL,DIM,jj)
    IMPLICIT NONE               !(MATRIZ,DIM,PONTO) PONTO=PONTO QUE DEU ORIGEM A MATRIZ.
                                !se a matriz não tiver origem em um ponto especifico, lance zero

INTEGER::i,J,DIM,INFO,jj    
CHARACTER*1::NORM
REAL*8::ANORM,RCOND,DLANGE
REAL*8,DIMENSION(:),ALLOCATABLE::WORK,WR,WI
INTEGER,DIMENSION(:),ALLOCATABLE::IWORK,IPIV
REAL*8,DIMENSION(:,:),ALLOCATABLE::KGLOBAL2,VL
REAL*8,DIMENSION(DIM,DIM)::KGLOBAL
REAL*8,DIMENSION(1)::WORK2    
    
ALLOCATE(WORK(4*DIM),IWORK(DIM))
ALLOCATE(KGLOBAL2(DIM,DIM),IPIV(DIM),WR(DIM),WI(DIM),VL(1,DIM))
KGLOBAL2=KGLOBAL


!os autovalores da matriz kglobal2 estao em WR(real) e WI(imaginaria)
!CALL DGEEV('N','N',3*NPT,KGLOBAL2,3*NPT,WR,WI,VL,1,VL,1,WORK,9*NPT,INFO)
!WRITE(*,*) WR
!WRITE(*,*) WI


NORM='1'
!dlange calcula a norma 1 da matriz kglobal 2
ANORM=DLANGE(NORM,DIM,DIM,KGLOBAL2,DIM,WORK2)
!WRITE(*,*) 'a norma 1 da matriz eh',ANORM

CALL DGETRF(DIM,DIM,KGLOBAL2,DIM,IPIV,INFO)
CALL DGECON('1',DIM,KGLOBAL2,DIM,ANORM,RCOND,WORK,IWORK,INFO)
IF(INFO.EQ.0)THEN
    if(rcond.lt.1.d-18)then
        WRITE(*,15) 'ponto',jj,'O COND. DA MATRIZ EH',RCOND
    endif
15 format (a5,1x,i4,3x,a21,1x,ES10.3)
ELSE
    WRITE(*,*) 'ERRO NO CALCULO DO CONDICIONAMENTO'
ENDIF

DEALLOCATE(KGLOBAL2,IPIV,WR,WI,VL)



END SUBROUTINE TESTA_CONDICIONAMENTO